// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"net/netip"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID         int64       `json:"id"`
	UserID     pgtype.Int8 `json:"user_id"`
	UserEmail  pgtype.Text `json:"user_email"`
	Action     string      `json:"action"`
	EntityType string      `json:"entity_type"`
	EntityID   int64       `json:"entity_id"`
	OldValues  []byte      `json:"old_values"`
	NewValues  []byte      `json:"new_values"`
	IpAddress  *netip.Addr `json:"ip_address"`
	UserAgent  pgtype.Text `json:"user_agent"`
	RequestID  pgtype.UUID `json:"request_id"`
	CreatedAt  time.Time   `json:"created_at"`
}

type Task struct {
	ID          int64              `json:"id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	AssigneeID  int64              `json:"assignee_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID        int64              `json:"id"`
	Email     string             `json:"email"`
	Password  string             `json:"password"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
