// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type AuditLog struct {
	ID         int64                 `json:"id"`
	UserID     sql.NullInt64         `json:"user_id"`
	UserEmail  sql.NullString        `json:"user_email"`
	Action     string                `json:"action"`
	EntityType string                `json:"entity_type"`
	EntityID   int64                 `json:"entity_id"`
	OldValues  pqtype.NullRawMessage `json:"old_values"`
	NewValues  pqtype.NullRawMessage `json:"new_values"`
	IpAddress  pqtype.Inet           `json:"ip_address"`
	UserAgent  sql.NullString        `json:"user_agent"`
	RequestID  uuid.NullUUID         `json:"request_id"`
	CreatedAt  time.Time             `json:"created_at"`
}

type Task struct {
	ID          int64          `json:"id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	AssigneeID  int64          `json:"assignee_id"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type User struct {
	ID        int64     `json:"id"`
	Email     string    `json:"email"`
	Password  string    `json:"password"`
	CreatedAt time.Time `json:"created_at"`
}
